/**
 * AI disclosure badge — shown next to AI-generated content.
 * Required for transparency under EU AI Act / emerging disclosure norms.
 */
export function AiBadge({ model = "AI" }: { model?: string }) {
  return (
    <span
      title={`This content was generated by ${model}. It may contain errors — review before acting.`}
      className="inline-flex items-center gap-0.5 rounded px-1.5 py-0.5 text-[10px] font-semibold bg-violet-100 text-violet-700 cursor-help"
    >
      ✦ {model}
    </span>
  );
}

/** Footer disclosure for panels with AI-generated content */
export function AiDisclosureFooter({ model = "Grok (xAI)" }: { model?: string }) {
  return (
    <p className="mt-2 text-[10px] text-neutral-400">
      ✦ Generated by {model}. AI output may be inaccurate — verify before acting.
    </p>
  );
}
